export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAILURE = "USER_LOAD_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const LEADERBOARD_REQUEST = "LEADERBOARD_REQUEST";
export const LEADERBOARD_REQUEST_SUCCESS = "LEADERBOARD_REQUEST_SUCCESS";
export const LEADERBOARD_REQUEST_FAILED = "LEADERBOARD_REQUEST_FAILED";

export const SCORE_CHANGE = "SCORE_CHANGE";
export const SET_SCORE_NULL = "SET_SCORE_NULL";
export const SET_QUIZ_TIMER = "SET_QUIZ_TIMER";
export const SELECT_ANSWER = "SELECT_ANSWER";

export const LOAD_QUIZ_REQUEST = "QUIZ_LOAD";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const LOAD_QUIZ_FAILED = "LOAD_QUIZ_FAILED";

export const UPDATE_USER_QUIZ_REQUEST = "UPDATE_USER_QUIZ_REQUEST";
export const UPDATE_USER_QUIZ_SUCCESS = "UPDATE_USER_QUIZ_SUCCESS";
export const UPDATE_USER_QUIZ_FAILED = "UPDATE_USER_QUIZ_FAILED";

export const ADD_QUIZ_REQUEST = "ADD_QUIZ_REQUEST";
export const ADD_QUIZ_REQUEST_SUCCESS = "ADD_QUIZ_REQUEST_SUCCESS";
export const ADD_QUIZ_REQUEST_FAILED = "ADD_QUIZ_REQUEST_FAILED";

export const HOMEPAGE_LOAD_QUIZ_REQUEST = "HOMEPAGE_LOAD_QUIZ_REQUEST";
export const HOMEPAGE_LOAD_QUIZ_SUCCESS = "HOMEPAGE_LOAD_QUIZ_SUCCESS";
export const HOMEPAGE_LOAD_QUIZ_FAILED = "HOMEPAGE_LOAD_QUIZ_FAILED";

export const USER_RECENT_QUIZ_REQUEST = "USER_RECENT_QUIZ_REQUEST";
export const USER_RECENT_QUIZ_SUCCESS = "USER_RECENT_QUIZ_SUCCESS";
export const USER_RECENT_QUIZ_FAILED = "USER_RECENT_QUIZ_FAILED";
export const SET_USER_NULL = "SET_USER_NULL";
