export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAILURE = "USER_LOAD_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const LEADERBOARD_REQUEST = "LEADERBOARD_REQUEST";
export const LEADERBOARD_REQUEST_SUCCESS = "LEADERBOARD_REQUEST_SUCCESS";
export const LEADERBOARD_REQUEST_FAILED = "LEADERBOARD_REQUEST_FAILED";
